- job:
    name: 'active-choice-example'

    parameters:
      - string:
          name: STR_PARAM
          default: test

      - active-choice:
          project: 'active-choice-example'
          name: ACTIVE_CHOICE_01
          description: "A parameter named ACTIVE_CHOICE_01 with options foo and bar."
          groovy:
              script: |
                  return ['foo:selected', 'bar']
              classpath: file:/tmp/aklsdjfkl.jar
              sandbox: false        
          fallback:
              script: |
                  return ['Error']
          visible-item-count: 1
          choice-type: single
          filterable:  true
          filter-length: 1

      - active-choice:
          project: 'active-choice-example'
          name: ACTIVE_CHOICE_02
          description: "A parameter named ACTIVE_CHOICE_02 with options foo and bar."
          groovy:
              script: |
                  return ['foo:selected', 'bar']
          fallback:
              script: |
                  return ['Error']
              sandbox: true    
              classpath: file:/tmp/aklsdjfkl.jar
          visible-item-count: 1
          choice-type: multi
          filterable:  false

      - active-choice:
          project: 'active-choice-example'
          name: ACTIVE_CHOICE_03
          description: "A parameter named ACTIVE_CHOICE_03 with options foo and bar."
          groovy:
              script: |
                  return ['foo:selected', 'bar']
          fallback:
              script: |
                  return ['Error']
              sandbox: true    
              classpath: file:/tmp/aklsdjfkl.jar
          visible-item-count: 1
          choice-type: radio

      - active-choice:
          project: 'active-choice-example'
          name: ACTIVE_CHOICE_04
          description: "A parameter named ACTIVE_CHOICE_04 with options foo and bar."
          groovy:
              script: |
                  return ['foo:selected', 'bar']
          fallback:
              script: |
                  return ['Error']
              sandbox: true    
              classpath: file:/tmp/aklsdjfkl.jar
          visible-item-count: 1
          choice-type: checkbox

      - active-choice:
          project: 'active-choice-example'
          name: ACTIVE_CHOICE_05
          description: "A parameter named ACTIVE_CHOICE_05 with options foo and bar."
          scriptler:
              script: print-path
              parameters:
                  - PARAM1:  value1 alksdjflksdf lkasjflk
                  - PARAM2:  value2
          visible-item-count: 1
          choice-type: checkbox

      - active-choice-reactive:
          project: 'active-choice-example'
          name: ACTIVE_CHOICE_REACTIVE_01
          description: "A parameter named ACTIVE_CHOICE_REACTIVE_01 with options foo and bar."
          groovy:
              script: |
                  return ['foo:selected', 'bar']
              classpath: file:/tmp/aklsdjfkl.jar
          fallback:
              script: |
                  return ['Error']
              classpath: file:/tmp/aklsdjfkl.jar,https://lakjsdfklsdjklf/lkajsdflk.jar
              sandbox: true    
          visible-item-count: 10
          reference: STR_PARAM
          choice-type: multi

      - active-choice-reactive:
          project: 'active-choice-example'
          name: ACTIVE_CHOICE_REACTIVE_02
          description: "A parameter named ACTIVE_CHOICE_REACTIVE_02 with options foo and bar."
          groovy:
              script: |
                  return ['foo:selected', 'bar']
              classpath: file:/your-path/your-classes.jar
              sandbox: true    
          reference: STR_PARAM,ACTIVE_CHOICE_01
          visible-item-count: 10
          choice-type: radio
          filterable:  true
          filter-length:  1

      - active-choice-reactive:
          project: 'active-choice-example'
          name: ACTIVE_CHOICE_REACTIVE_03
          description: "A parameter named ACTIVE_CHOICE_REACTIVE_03 with options foo and bar."
          scriptler:
              script: print-path
              parameters:
                  - PARAM1:  value1 aklfsdj kalsjflk
                  - PARAM2:  value2
          reference: STR_PARAM
          visible-item-count: 10
          choice-type: checkbox

      - active-choice-reactive:
          project: 'active-choice-example'
          name: ACTIVE_CHOICE_REACTIVE_04
          description: "A parameter named ACTIVE_CHOICE_REACTIVE_04 with options foo and bar."
          scriptler:
              script: print-path
          reference: STR_PARAM
          visible-item-count: 10
          choice-type: checkbox

      - active-choice-reactive-reference:
          name: ACTIVE_CHOICE_REACTIVE_REF_01
          project: 'active-choice-example'
          description: "A parameter named ACTIVE_CHOICE_REACTIVE_REF_01 with options foo and bar."
          groovy:
              script: |
                  return ['foo:selected', 'bar']
              classpath: file:/tmp/aklsdjfkl.jar
              sandbox: true    
          fallback:
              script: |
                  return ['Error']
              classpath: file:/tmp/aklsdjfkl.jar,http://lakjsdfklsdjklf/lkajsdflk.jar
          reference: STR_PARAM
          omit-value: false
          choice-type: input-text

      - active-choice-reactive-reference:
          name: ACTIVE_CHOICE_REACTIVE_REF_02
          project: 'active-choice-example'
          description: "A parameter named ACTIVE_CHOICE_REACTIVE_REF_02 with options foo and bar."
          groovy:
              script: |
                  return ['foo:selected', 'bar']
              classpath: file:/tmp/aklsdjfkl.jar
              sandbox: true    
          fallback:
              script: |
                  return ['Error']
              classpath: file:/tmp/aklsdjfkl.jar,http://lakjsdfklsdjklf/lkajsdflk.jar
          reference: STR_PARAM,ACTIVE_CHOICE_01
          omit-value: false
          choice-type: numbered-list

      - active-choice-reactive-reference:
          name: ACTIVE_CHOICE_REACTIVE_REF_03
          project: 'active-choice-example'
          description: "A parameter named ACTIVE_CHOICE_REACTIVE_REF_03 with options foo and bar."
          groovy:
              script: |
                  return ['foo:selected', 'bar']
              classpath: file:/tmp/aklsdjfkl.jar
              sandbox: true    
          fallback:
              script: |
                  return ['Error']
              classpath: file:/tmp/aklsdjfkl.jar,http://lakjsdfklsdjklf/lkajsdflk.jar
          reference: STR_PARAM
          omit-value: false
          choice-type: bullet-list

      - active-choice-reactive-reference:
          name: ACTIVE_CHOICE_REACTIVE_REF_04
          project: 'active-choice-example'
          description: "A parameter named ACTIVE_CHOICE_REACTIVE_REF_04 with options foo and bar."
          groovy:
              script: |
                  return ['foo:selected', 'bar']
              classpath: file:/tmp/aklsdjfkl.jar
              sandbox: true    
          fallback:
              script: |
                  return ['Error']
              classpath: file:/tmp/aklsdjfkl.jar,http://lakjsdfklsdjklf/lkajsdflk.jar
          reference: STR_PARAM
          omit-value: false
          choice-type: formatted-html

      - active-choice-reactive-reference:
          name: ACTIVE_CHOICE_REACTIVE_REF_05
          project: 'active-choice-example'
          description: "A parameter named ACTIVE_CHOICE_REACTIVE_REF_05 with options foo and bar."
          groovy:
              script: |
                  return ['foo:selected', 'bar']
              sandbox: true    
          fallback:
              script: |
                  return ['Error']
              classpath: file:/tmp/aklsdjfkl.jar,http://lakjsdfklsdjklf/lkajsdflk.jar
          reference: STR_PARAM
          omit-value: false
          choice-type: formatted-hidden-html

      - active-choice-reactive-reference:
          project: 'active-choice-example'
          name: ACTIVE_CHOICE_REACTIVE_REF_06
          description: "A parameter named ACTIVE_CHOICE_REACTIVE_REF_06 with options foo and bar."
          scriptler:
              script: print-path
              parameters:
                  - PARAM1: value1
          reference: STR_PARAM
          visible-item-count: 10
          choice-type: input-text 

      - active-choice-reactive-reference:
          project: 'active-choice-example'
          name: ACTIVE_CHOICE_REACTIVE_REF_07
          description: "A parameter named ACTIVE_CHOICE_REACTIVE_REF_07 with options foo and bar."
          scriptler:
              script: print-path
          reference: STR_PARAM
          visible-item-count: 10
          choice-type: input-text 

